### ISSUE TITLE
Need to test: App doesnt go to foreground when data is sent

### ISSUE THREAD

**Issue by cihanwoicke** [pbudner/pebble-happimeter#1]
[pebble-happimeter:master] 1 new commit by inesrieger:
`f6da3de`  App doesn't go to foreground when data is send - inesrieger

**Comment by pbudner** [comment]
Found out that the app has to stay in foreground until the data sending process is finished..
Thus, I created a "Uploading data.."-window that also serves as an error catcher when the upload takes too long (usually < 2 seconds) it shows a warning that the watch should be connected to the phone and that the Pebble app should be opened.

To summarize, the following three conditions are necessary for data uploading:
1.  Happimeter app has to be in the foreground
2. Pebble has to be connected to the phone
3. The Pebble app on the phone must be opened (but must not be in the foreground)
